application:
  security:
    cors: '[ { "pattern": "/**", "origins": [ "*" ], "methods": [ "*" ], "headers": [ "*" ] } ]'
  localization:
    time:
      zone-id: America/Bogota
  json:
    format:
      local-date: yyyy-MM-dd'T'HH:mm:ss.SSSX
      local-time: yyyy-MM-dd'T'HH:mm:ss.SSSX
      local-datetime: yyyy-MM-dd'T'HH:mm:ss.SSSX

  message:
    amqp:
      uri: amqps://woodpecker.rmq.cloudamqp.com/jmodcbnq
      username: jmodcbnq
      password: y9TkU5HAx6xp6cHod7Gv1lfUwe0vevIF
      topic-exchange-name: profile-exchange
      queue-name: profile-reader-queue
      default-exchange-topic: joiner.profile.new
      default-queue-topic: joiner.profile.amend

# ---------------

server:
  servlet:
    context-path: /wap/profile-reader
  port: 8091
